### ISSUE TITLE
Move into "ember-cli" org

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-mocha#113]
If the switchfly people are okay with it I would like to propose moving this repo (and the related ones) into the `ember-cli` GitHub organization. At the moment it seems that @rwjblue is the only maintainer, which obviously doesn't scale very well. Moving the repo should hopefully increase visibility and distribute the maintenance workload on more shoulders.

**Comment by yads** [comment]
I would be interested in maintaining this project if @rwjblue needs help with it.

**Comment by Turbo87** [comment]
@rwjblue any news on this?

**Comment by dgeb** [comment]
The Ember Core Team decided it would like to consolidate the officially supported testing repos in community-controlled repos to improve visibility and control. At the same time, we want to continue to recognize the importance of the investment that Switchfly made to get these projects off the ground.

I have contacted @pchen12 from Switchfly to discuss moving `ember-test-helpers` and `ember-mocha` to the `emberjs` org, and `ember-cli-mocha` to the `ember-cli` org. @rwjblue has already moved `ember-qunit` over to `emberjs`.

**Comment by pchen12** [comment]
@dgeb @Turbo87 I am no longer working at Switchfly.  I recommend contacting Sonali Varde at svarde@switchfly.com.  Personally, I agree with the recommendation.  I'll loop Sonali into this conversation.

**Comment by pchen12** [comment]
Sonali,

The Ember Core Team would like to move the above mentioned projects from
under the Switchfly GitHub org to the Ember GitHub org.  I told Dan that
this is something Switchfly/you will need to OK.  Given Switchfly hasn't
contributed further on these projects, my two cents is to move the project
ownership.

All the best,
Paul

**Comment by dgeb** [comment]
@pchen12 Thanks for the update and the recommendation. I'll also get in touch with Sonali via email in case she doesn't see this issue.

**Comment by Turbo87** [comment]
@dgeb any response so far?

**Comment by dgeb** [comment]
@Turbo87 Switchfly's developers were tied up last week. But thanks for the reminder - I just followed up now.

**Comment by Turbo87** [comment]
done! 🎉
