### ISSUE TITLE
Avoid writing JSHint ignore on generated files

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli-mocha#117]
I'm using ESLint for my Ember project and really wish the blueprints here wouldn't dump

``` js
/* jshint expr:true */
```

at the top of all of my test files.  I understand why it's done, but it's a bit annoying for those of us not using JSHint.

It should be possible to only add it if the `ember-cli-jshint` package is installed (or maybe try to detect `ember-cli-eslint` and prevent writing it if it's present).  It seems like it should be possible to use [custom file tokens](https://ember-cli.com/extending/#indexjs) to contain the JSHint expression (or nothing) and use the blueprint system to write the line (or not) dynamically.

**Comment by Dhaulagiri** [comment]
Fixed by https://github.com/ember-cli/ember-cli-mocha/pull/118
