### ISSUE TITLE
Remove ember-cli-test-loader from bower.json

### ISSUE THREAD

**Issue by nucleartide** [ember-cli/ember-cli-mocha#122]
I'm on Ember 2.7, and I get a deprecation warning after installing ember-cli-mocha:

```
DEPRECATION: ember-cli-test-loader should now be included as an NPM module with version 1.1.0 or greater.
```

It'd be nice to remove [this line](https://github.com/switchfly/ember-cli-mocha/blob/master/blueprints/ember-cli-mocha/index.js#L19), but I'm not sure how that might affect people using versions of Ember prior to 2.7.

**Comment by Turbo87** [comment]
@nucleartide Previous versions of Ember CLI already included the test loader in `bower.json` anyway (see https://github.com/ember-cli/ember-cli/blob/v2.6.3/blueprints/app/files/bower.json#L6), so I'm not sure why it was added here too. IMHO we can remove that line. Could you open a PR that removes it?

**Comment by Turbo87** [comment]
actually, just removing it might not be such a great idea. we should try to mimic what has been done in https://github.com/ember-cli/ember-cli-qunit/commit/115d56bff12ad01ef08c34a1ae9f9011e7e6904b instead.

**Comment by alexlafroscia** [comment]
If I understand correctly, we should be able to add `ember-cli-test-loader` as a dependency of `ember-cli-mocha` and then expose it using the [`shouldIncludeChildAddon`](https://ember-cli.com/api/classes/Addon.html#method_shouldIncludeChildAddon) hook instead, allowing us to avoid adding the dependency to the consuming application entirely.
