### ISSUE TITLE
Release v0.11.0

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-mocha#128]
`ember-cli-jshint` has been extracted for quite some time, but we still haven't released that change. 

/cc @dgeb @rwjblue

**Comment by Patsy-issa** [comment]
bump.

**Comment by Turbo87** [comment]
@rwjblue now that I have commit bit here I'd like to release this. only thing missing now is NPM permission on this package.

**Comment by Turbo87** [comment]
```
$ npm publish
+ ember-cli-mocha@0.11.0
```
