### ISSUE TITLE
Remove dep on ember-cli-shims

### ISSUE THREAD

**Issue by jasonmit** [ember-cli/ember-cli-mocha#131]
https://github.com/tomdale/rfcs/blob/js-modules/text/0000-javascript-module-api.md proposes changing how we import modules.  I've begun to undo my personal use of ember-cli-shims in anticipation and realized this addon requires it.

Used here: https://github.com/ember-cli/ember-cli-mocha/blob/master/index.js#L183-L185

I can send a PR if there is interest.

**Comment by Turbo87** [comment]
given that https://github.com/ember-cli/ember-cli-shims/blob/master/test-shims.js is empty and has been empty since Feb 2015 we should definitely remove that!

**Comment by alexlafroscia** [comment]
I'd be happy to put the PR together if you want @jasonmit

**Comment by jasonmit** [comment]
@alexlafroscia 👍 please do
