### ISSUE TITLE
Split "chai" code into ember-cli-chai 

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-mocha#132]
Mocha is often used in combination with Chai, but it is not required and some people might prefer other assertion libraries. Should we split this library into `ember-cli-mocha` and `ember-cli-chai`?

/cc @dgeb @rwjblue @stefanpenner @alexlafroscia

**Comment by rwjblue** [comment]
Seems fine to me, but the default out of the box experience should be "it works" IMO.

**Comment by alexlafroscia** [comment]
Ehh, I personally feel like that would be unnecessary.  Having to install one thing is simpler for most people and using Chai with Mocha is probably what most people want.  If they want to use another assertion library, they can always do so and just ignore Chai. It's not like having extra test assets affect that apps' payload size.

**Comment by Turbo87** [comment]
@alexlafroscia the problem is that we would have to do a major release for every major release of Mocha *and* Chai. also we could still add `ember-cli-chai` via blueprint by default.

**Comment by alexlafroscia** [comment]
Ahh, didn't really think about it from the dependency-version perspective... That's definitely a good "pro" in favor of it.

Would it be possible to make a PR to Chai so that it didn't require an Ember add-on at all? Do we have any Chai code that specifically make it work with Ember, or is it just exposing the `chai` module for people to import?

**Comment by Turbo87** [comment]
> Do we have any Chai code that specifically make it work with Ember, or is it just exposing the chai module for people to import?

I think it's just exposing `chai` to our import system (see https://github.com/ember-cli/ember-cli-mocha/search?utf8=%E2%9C%93&q=chai)

> Would it be possible to make a PR to Chai so that it didn't require an Ember add-on at all?

Until we can just import NPM modules directly we will have to wrap them in EmberCLI addons and I doubt that this will be accepted in the main Chai repository... 🤔

**Comment by alexlafroscia** [comment]
I see. I was hoping that, if we added support for a named AMD module to Chai, then we could just do the without the wrapper 😔

**Comment by Turbo87** [comment]
in the case of `ember-cli-chai` you'd just have to run `ember install ember-cli-chai` and then you're done.

in the case of AMD-compatible Chai you'd still have to import Chai into the test vendor tree somehow and it would be quite a bit more complex for our users. also there wouldn't be a good place to put the instructions on how to do that since they don't really belong in the Chai repo itself.

**Comment by alexlafroscia** [comment]
Right, right. Kind of a shame it isn't easier to consume an AMD-exporting dependency without a wrapper add-on, but you're right about the ease of the `ember install ember-cli-chai` being worth it.

**Comment by Turbo87** [comment]
@alexlafroscia another good reason for splitting is https://github.com/ember-cli/ember-cli-chai/issues/3 (using with Chai with QUnit)
