### ISSUE TITLE
use should() with chai

### ISSUE THREAD

**Issue by shaunc** [ember-cli/ember-cli-mocha#14]
I'm having trouble using should() with chai -- can't seem to import it? Could you add to the doc? Also, if we want to globally initialize chai.should(), where should the code go?

**Comment by jonathanKingston** [comment]
:+1: to exposing Chai internals in each test (which seems to be the way ember-cli is suggesting to write qunit tests).

Personally for me assert has the most sane syntax as for BDD code a real BDD assertion library should be used external to these tests where by business can drive the tests like cucumber.

So I would like to be able to do:
```
import { assert } from 'ember-mocha';
```

Or similar.

**Comment by dgeb** [comment]
So, we've just introduced a `chai` module in `ember-mocha` that exports `expect` and `assert`. Both @rwjblue and I were wary to export `should` alongside these two, as discussed here: https://github.com/switchfly/ember-cli-mocha/issues/37#issuecomment-75460873

To semi-officially support `should`, we could just add a suggestion to the README to add `window.chai.should();` to `test-helper.js`. Of course accessing a global like this is pretty hackish when everything else is modularized.

We could also export `should` through a new shim module in ember-mocha (perhaps `chai-should`?). If anyone really wants this, let's have the discussion here or in ember-mocha. Of course, such a shim could be added to a completely separate lib even if we decide against including it in ember-mocha.

**Comment by Turbo87** [comment]
This should be covered by ember-cli-chai now.
