### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by blipntime** [ember-cli/ember-cli-mocha#140]
The package.json we got from npm has "version": "0.11.0" and "ember-mocha": "^0.8.11",  while master has "version": "0.11.0" and "ember-mocha": "^0.9.1". When are you going to push to npm a new release?

**Comment by Turbo87** [comment]
```
$ npm publish
+ ember-cli-mocha@0.12.0
```

**Comment by blipntime** [comment]
Thanks.
