### ISSUE TITLE
mochas require() overwrites embers require()

### ISSUE THREAD

**Issue by rox163** [ember-cli/ember-cli-mocha#141]
I am running tests with ember-cli-code-coverage on and using ember-cli-mocha and mocha. Mocha is setting ember's global require() to its own function. This makes the coverage reporting fail in the script inserted into tests/index.html. Since global require() is no longer ember's function.
Come to this conclusion based on https://github.com/curit/ember-cli-yadda/issues/30 describing similar behaviour

**Comment by Turbo87** [comment]
@rox163 can you point us to the code that overwrites `require` in Mocha?

**Comment by rox163** [comment]
Bit of a newbie at trying to investigate this type of stuff so apologies for unclear info. I'm not sure but here I think there is a require declared? https://github.com/mochajs/mocha/blob/master/mocha.js#L1

**Comment by Turbo87** [comment]
@rox163 do you have a repository somewhere that reproduces this issue?

**Comment by rox163** [comment]
I'll have to set one up since I have pinned all my repos to v0.3.5 of code coverage to get them working.

**Comment by Turbo87** [comment]
@rox163 any news on this? Without being able to reproduce the issue we can't fix it

**Comment by job13er** [comment]
@rox163 I don't think it was `mocha` doing the overriding. See my notes on https://github.com/kategengler/ember-cli-code-coverage/issues/75, I'm pretty sure `ember-code-snippet` is the culprit, b/c of `broccoli-browserify`.

**Comment by Turbo87** [comment]
@job13er thanks for the feedback. closing this for now.
