### ISSUE TITLE
Expose methods for stubbing injections

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli-mocha#147]
When testing with QUnit, you have the ability to stub out services using `this.register` and `this.inject.service`. The docs on it can be found [here](https://guides.emberjs.com/v2.9.0/testing/testing-components/#stubbing-services) (scroll down to "Stubbing Services").

As far as I know, you there is no way to access this API when using Mocha for testing. It would be really nice to enable this, although I'm not sure if it's more of a concern of `ember-cli-mocha` or `ember-cli-chai`.

I'm happy to take a look at getting this working myself; just wanted to make an issue to track progress and get feedback.

**Comment by alexlafroscia** [comment]
Huh, never mind. Last time I tried this, it didn't work, but it seems to now ¯\\_(ツ)_/¯

**Comment by rwjblue** [comment]
Awesome!
