### ISSUE TITLE
Using `before` and `after`

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli-mocha#165]
It seems like `before` and `after` are treated differently than `beforeEach` and `afterEach`.  Is that done intentionally?  For example, I can't access `this.container` within a `before` function that way I can in `beforeEach`.

**Comment by Turbo87** [comment]
@alexlafroscia the `container` is setup in its own `beforeEach()` block, which runs after all `before()` blocks, so yes, this is intentional.

**Comment by alexlafroscia** [comment]
Okay, I see. So as a general principle, anything that needs the container should be done on a per-test basis?

In hindsight this makes perfect sense, I just came across some stuff in our codebase when updating to the new test API that was using the container in a `setup` hook and wasn't sure how to port that over.

**Comment by Turbo87** [comment]
@alexlafroscia yes, that's what I'm suggesting

**Comment by alexlafroscia** [comment]
Great, thanks for your help @Turbo87!
