### ISSUE TITLE
Customizing the grep pattern to always run TestLoader

### ISSUE THREAD

**Issue by matthewconstantine** [ember-cli/ember-cli-mocha#170]
Most of our developers use a grep pattern match their feature area while developing. However, when TestLoader fails, no error is reported. For example `import blah from 'unreal-file-that-does-not-exist';` silently fails if a developer is using `grep=MyComponent`. 

We'd like to see if there's an easy way to append `|TestLoader` to our greps. That way a `grep=MyComponent` would become `grep=MyComponent|TestLoader`.

I saw `overrideTestCommandFilter` in [index.js](https://github.com/ember-cli/ember-cli-mocha/blob/3cc46b5e25a8e1e8d86779a422e7da4f2b38b86c/index.js#L23-L29). Is there a straightforward way extend ember-cli-mocha (or a more appropriate place) to do this?

**Comment by Turbo87** [comment]
unfortunately I don't think there is currently an easy way to do anything like that, sorry.
