### ISSUE TITLE
updating project to ember-cli@2.12.1 seems to fail on untranspiled ember-mocha in vendor.js

### ISSUE THREAD

**Issue by efx** [ember-cli/ember-cli-mocha#189]
This is a private repo, so i can't post the config. Mocha specific dependencies:
* ember-cli-mocha@0.13.1
* ember-mocha@0.8.11 (also tried bumping to ember-mocha@0.11.0
* ember-cli@2.11.1

When I try to update to ember-cli@2.12.1, running ember test --server  is broken. Navigating to localhost:7357 serves up `app/index.html`. 
Devtools Console output:
<img width="1438" alt="screen shot 2017-04-17 at 5 29 27 pm" src="https://cloud.githubusercontent.com/assets/472721/25105632/7cc28bf4-2393-11e7-95a2-772a481f4c81.png">
Relevant capture of `test-support.js`:
<img width="1236" alt="screen shot 2017-04-17 at 5 32 34 pm" src="https://cloud.githubusercontent.com/assets/472721/25105723/e00f6984-2393-11e7-818a-5926ebed4954.png">
I've tried bumping versions but am getting nowhere. Is there a specific incompatibility between ember-mocha, ember-cli-mocha, and ember-cli? I can try putting the dependencies into a fake repo if helpful.

**Comment by Turbo87** [comment]
what version of `ember-test-helpers` do you have?

/cc @rwjblue

**Comment by Dhaulagiri** [comment]
We had the same problem.  I think you have to also upgrade ember-cli-mocha to 0.13.2 for it to work with ember-cli 2.12.

**Comment by Turbo87** [comment]
@Dhaulagiri right, thanks for figuring that out. I somehow thought `0.13.1` was the latest release, but you are right that `0.13.2` (including https://github.com/ember-cli/ember-cli-mocha/pull/166) should fix this issue.

**Comment by efx** [comment]
thanks, that resolved it.
