### ISSUE TITLE
Invert not working as expected

### ISSUE THREAD

**Issue by campbecf** [ember-cli/ember-cli-mocha#213]
```
  --invert (Boolean) (Default: false) Invert the filter specified by the --filter argument
    aliases: -i
```

Maybe I am using this command wrong, but it doesn't seem to be inverting my filters. Does it still function? I get some unusual behaviors if I do `--invert=false` with a filter as well, but isn't that the default?

**Comment by efx** [comment]
I'm seeing this as well when running in combination with the `-f` flag. @Turbo87 any idea as to what causes this/ how to resolve?

**Comment by Turbo87** [comment]
> any idea as to what causes this/ how to resolve?

not right now. I'm focusing on the `ember-mocha` addon conversion for now, and after that reasoning about bugs and features should become massively simpler.

**Comment by efx** [comment]
excellent, thanks for the update @Turbo87.
