### ISSUE TITLE
What are the instructions?

### ISSUE THREAD

**Issue by micky2be** [ember-cli/ember-cli-mocha#219]
ember-mocha sends me here to follow instruction about how to install stuff but there is nothing here.
Do I still need to install ember-mocha itself?
How do I setup my tests?

**Comment by Turbo87** [comment]
> how to install stuff but there is nothing here

see https://github.com/ember-cli/ember-cli-mocha#installation

> How do I setup my tests?

once you have `ember-cli-mocha` installed e.g. `ember generate component-test` should automatically generate a test for you using Mocha instead of QUnit
