### ISSUE TITLE
[Beta] regression in integration tests w/ async ember-data relationships

### ISSUE THREAD

**Issue by simonihmig** [ember-cli/ember-cli-mocha#233]
@Turbo87 this is the regression I mentioned yesterday on Slack. I finally got a minimal reproduction together: https://github.com/simonihmig/ember-mocha-demo

The failing test is this one: https://github.com/simonihmig/ember-mocha-demo/blob/master/tests/integration/components/my-component-test.js#L39-L42.

In the `beforeEach` I load a model `parent`, that has an async relationship to `child`. The loading of the `child` happens in the template: https://github.com/simonihmig/ember-mocha-demo/blob/master/app/templates/components/my-component.hbs#L4.
The test itself is passing, but some async callback of ember-data seems to run after the test has finished, causing a `set on destroyed object` error:

![image](https://user-images.githubusercontent.com/1325249/33741967-b1073240-dba6-11e7-8158-d8529c450f21.png)

The following screenshot shows the `_find` function which seems to load the `child` record. As you can see this happens before the test's assertion:

![image](https://user-images.githubusercontent.com/1325249/33742041-ee81dfa8-dba6-11e7-8617-115a4ca14e4e.png)

The other breakpoint is within the `then` callback, and this happens after the assertion, and apparently after the test has been teared down, as the call to `serializerForAdapter` is causing the afore mentioned exception (the jsonapi serializer has already been destroyed, when it tries to set the `store` on it):

![image](https://user-images.githubusercontent.com/1325249/33742179-6d8bc0a2-dba7-11e7-8099-cb8c377ad42f.png)

Adding `await wait()` fixes this: https://github.com/simonihmig/ember-mocha-demo/blob/master/tests/integration/components/my-component-test.js#L39-L42. So seems there is still some pending promise or run loop that is not correctly waited for before tearing down the test? 

Also, when downgrading to `0.14.4` this error does not show up. As you said already, the root issue might be caused by the larger upstream changes in `ember-test-helpers`, but I filed this here for now...

**Comment by rwjblue** [comment]
@simonihmig - Can you confirm that https://github.com/emberjs/ember-test-helpers/pull/263 (which was released in `@ember/test-helpers@0.7.4`) fixes your real app also?

**Comment by simonihmig** [comment]
@rwjblue sure, wanted to do that already, but didn't find the time yet. Hopefully tomorrow, will keep you updated!

**Comment by simonihmig** [comment]
@rwjblue all tests are ✅  ✅  ✅     👏
