### ISSUE TITLE
Ember CLI 2.17+ support?

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli-mocha#240]
Ember CLI 2.17 blueprint [removes resolver](http://www.ember-cli-diff.org/?#/v2.16.2/v2.17.0).

Now, integration tests fail with:

> Error: you must set a resolver with `testResolver.set(resolver)`

PS I was gonna convert to QUnit, but Chai [no longer supports](https://github.com/ember-cli/ember-cli-chai#qunit) QUnit! :astonished:

**Comment by Turbo87** [comment]
see https://github.com/ember-cli/ember-cli-mocha/issues/231

**Comment by lolmaus** [comment]
@Turbo87, that issue is closed, yet the fix is not released and not even merged into `master`. :/

**Comment by Turbo87** [comment]
it will be released once https://github.com/ember-cli/ember-cli-mocha/pull/239 is decided upon
