### ISSUE TITLE
Acceptance test blueprint failing  out of the box for addons with ember-source@3.1.beta

### ISSUE THREAD

**Issue by mattmarcum** [ember-cli/ember-cli-mocha#249]
Wasn't sure if I should open the here on on ember-source, wanted to see what people on this repo though first.

I was having some problems getting ember-cli-mocha working on an addon so I spun up a new addon named `tester` using  ember-cli#master and installed ember-cli-mocha.  I then generated an `admin` route and an `admin` acceptance test.  The tests fails with this:

Error: Could not find module `tester/tests/helpers/start-app` imported from `dummy/tests/acceptance/admin-test`missingModule@assets/vendor.js:250:11 There are also some linting errors about `visit`,`andThen`, and `currentURL` not being found.  

Looks like this addon hasn't been updated to be compatible with the latest test-helpers or something?  Maybe related to this? https://github.com/ember-cli/ember-cli-mocha/issues/188

**Comment by Turbo87** [comment]
if you use the latest `ember-cli-mocha` then it should recreate the `start-app.js` file for you again due to https://github.com/ember-cli/ember-cli-mocha/blob/v0.15.0/blueprints/ember-cli-mocha/files/tests/helpers/start-app.js. how did you install `ember-cli-mocha`?

**Comment by mattmarcum** [comment]
Yup, that was it - I cloned ember-cli-mocha and `yarn linked` it into my app and re-ran the ember-cli-mocha generator and that fixed it.  Thanks.
