### ISSUE TITLE
Intent to support linting flag

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli-mocha#44]
Would it be possible to allow the linting to be either disabled or configured?

With the support for the lintTree for addons to hook into now, it seems to make sense that it could be turned off.

I ask as I would like to swap out with my own: https://github.com/jonathanKingston/ember-cli-eslint

@rwjblue what do you think about this for ember-cli-qunit also?

**Comment by jonathanKingston** [comment]
I think this would probably mean adding in a config value into lintTree for this to be configurable.

**Comment by jonathanKingston** [comment]
I think this might be better as an ember-cli rfc as I would like it if I could automatically raise test failures from the linting too.

**Comment by jonathanKingston** [comment]
@dgeb any interest from you on this one?

**Comment by dylanfoster** [comment]
Any thoughts on this? I'd also like to swap out jshint for ember-cli-eslint

**Comment by jonathanKingston** [comment]
@dylanfoster it might be better to register your support/comments on the RFC here: https://github.com/ember-cli/rfcs/pull/15

Thanks

**Comment by Turbo87** [comment]
closing in favor of ember-cli/rfcs#15
