### ISSUE TITLE
Consider setting expr:true in tests/.jshintrc to avoid chai warnings

### ISSUE THREAD

**Issue by dgeb** [ember-cli/ember-cli-mocha#6]
A single global setting would be cleaner than https://github.com/switchfly/ember-cli-mocha/commit/18b40d0d25727c9b36208bcee8644d20f48fb3e7, but are there any downsides to consider?

**Comment by Turbo87** [comment]
since `ember-cli-chai` is a standalone addon now we should do it in there, or at least mention it in the README
