### ISSUE TITLE
Href to grep tests incorrect when running in browser

### ISSUE THREAD

**Issue by grese** [ember-cli/ember-cli-mocha#61]
When I run my tests in the browser (by visiting localhost:4200/tests?coverage=true), everything works fine, but if I try to click on one of the links reported by mocha (to view that specific set of tests), the browser redirects me back to "/?grep=<MODULE_NAME>".

I did a little inspecting of the HTML on the mocha test results page, and it looks like the links are being created as "href=?grep=<MODULE_NAME>", but I believe the correct link should be "href=/tests?grep=<GREP_STRING>".

**Comment by dwickern** [comment]
:+1: this is really annoying

**Comment by Turbo87** [comment]
apparently this was fixed by https://github.com/sglanzer/ember-cli-blanket/pull/91. thanks @dwickern!
