### ISSUE TITLE
Warn when bowers deps are out of sync

### ISSUE THREAD

**Issue by blimmer** [ember-cli/ember-cli-mocha#63]
I just noticed that I was using `^0.8.0` for `ember-cli-mocha` but the bower dependency was at `~0.5.1`. We should add a warning that tells the user to run `ember g ember-cli-mocha` when these are out of whack.

**Comment by alexlafroscia** [comment]
Do you mean when the versions of `ember-mocha` and `ember-cli-mocha` don't match?  I don't think they're supposed to...

**Comment by blimmer** [comment]
Hmm it looks like it's not a bower dependency [anymore](https://github.com/switchfly/ember-cli-mocha/commit/1719e575d0300b4c874a23fd59f3c92b7ff49af0), however the same concern still exists for other bower dependencies defined in the addon [blueprint](https://github.com/switchfly/ember-cli-mocha/blob/f30f9695930f0d602d2f2e66913c13d4824d1805/blueprints/ember-cli-mocha/index.js#L15-L20).

If the user updates the addon by bumping the number in the package.json or using greenkeeper, they'll miss out.

It's not necessarily just a problem with this project, but could potentially cause problems.

**Comment by alexlafroscia** [comment]
Yeah, that doesn't sound like an issue for this project... If you're using Greenkeeper to automate your NPM dependencies, you'd probably want something to do the same for your Bower ones too.  Any addon that adds Bower dependencies has this same problem.

**Comment by alexlafroscia** [comment]
I wonder if all of these Bower dependencies could be managed by NPM instead...

**Comment by Turbo87** [comment]
@alexlafroscia yes, they should. and I agree that this is not an issue that this addon has to solve itself.
