### ISSUE TITLE
Filter out JSHint specs

### ISSUE THREAD

**Issue by maxcal** [ember-cli/ember-cli-mocha#70]
Is there some way to filter out the JSHint specs from the test reporter? I find it hard to actually find my more meaningful specs amongst the noise.

**Comment by blimmer** [comment]
I don't think we currently support this, but it wouldn't be terribly difficult to do.

[Here's](https://github.com/switchfly/ember-cli-mocha/blob/42cc756f61afecafeaba7fc4ea9fc37a4ca629ae/index.js#L119) where they get generated.

**Comment by rwjblue** [comment]
You can use an inverse filter.

**Comment by blimmer** [comment]
Ah, rwjblue is right, that would be a good workaround. @maxcal to do this run:
```
ember t -f "JSHint" -i
```

I do, however, think turning off auto-generated JSHint tests could be useful for some.

**Comment by rwjblue** [comment]
@blimmer - Yeah, no argument there (might make sense as an ember-cli wide flag though and not just for ember-cli-mocha).  I was just pointing out that the inverse would work for now.

**Comment by blimmer** [comment]
Definitely - no problem. I was just pointing that out in case maxcal wanted to contribute :-)

**Comment by maxcal** [comment]
Thanks. I might look into experimenting with `testGenerator` and nesting all the JSHint specs into a single describe group.

**Comment by maxcal** [comment]
It would definatly be less intrusive if the generated tests where something like:

```JS
describe("JSHint", function(){
  it(relativePath + ' should pass JSHint', function(){
    expect(" + !!passed + ", '" + relativePath + " should pass jshint." + errors + "').to.be.ok;
  }); 
  // ... the rest of the JSHint specs
});
```

**Comment by maxcal** [comment]
How is the `lintTree` injected into the compiled tests?

**Comment by blimmer** [comment]
They're created/injected in the code snippet I posted above.

**Comment by Turbo87** [comment]
this has been fixed inside of `ember-cli-eslint` now. feel free to port the same thing to `ember-cli-jshint`
