### ISSUE TITLE
mocha parallel

### ISSUE THREAD

**Issue by mmahalwy** [ember-cli/ember-cli-mocha#78]
It'd be awesome to run the tests in parallel - this is a great plugin for example

https://github.com/atsuya/parallel-mocha

**Comment by Turbo87** [comment]
@mmahalwy that can't work. that plugin is only relevant for node-based tests, but we're actually running the tests in the browser or via phantomjs.

**Comment by Turbo87** [comment]
https://github.com/trentmwillis/ember-exam might work instead

**Comment by mmahalwy** [comment]
@Turbo87 this is awesome! Only works with Qunit?

**Comment by Turbo87** [comment]
apparently only for QUnit right now, but AFAIK they are working on Mocha support (see https://github.com/trentmwillis/ember-exam/issues/47)
