### ISSUE TITLE
Error: Cannot re-register: `service:store`, as it has already been resolved.

### ISSUE THREAD

**Issue by spinlock99** [ember-cli/ember-cli-mocha#80]
First: sorry if this is the wrong place for this question. Just point me to the right resources if this isn't an issue with ember-cli-mocha

I'm getting the error: `Error: Cannot re-register:`service:store`, as it has already been resolved.` when I try to run this acceptance test:

```
# jshint expr:true
`import Ember from 'ember'`
`import startApp from '../../helpers/start-app'`

describe "Acceptance: AccountProfile", ->
  before ->
    @App = startApp()
    return

  after ->
    Ember.run(@App, "destroy")


  it "can visit /account/profile", (done) ->
    visit "/account/profile"
    andThen ->
      expect(currentPath()).to.equal "account/profile"
    done()
```

The error is happening in the "after all" hook so I assume that is when the `@App` is being destroyed. I'm at a loss here. I assume the error is EmberData trying to reregister itself but I don't know why I'm getting that when I try to destroy the app.

Any help would be greatly appreciated.

Thanks!

**Comment by rwjblue** [comment]
My guess is that it is related to https://github.com/emberjs/data/pull/3690

**Comment by spinlock99** [comment]
Thanks!

I've got a hacky work-around to rebuild the registry before calling destroy in the `after` block:

      after ->
        @App.registry = @App.buildRegistry()
        Ember.run(@App, "destroy")

That gives me the same results as the ember-data patch you linked to but I don't have to maintain a patched version of ember-data.

But, now I'm getting this error:

    Acceptance: AccountProfile
    can visit /account/profile ‣
    "after all" hook ‣
    TypeError: app.testHelpers.wait is not a function
        at visit (assets/vendor.js:53338:28)
        at assets/vendor.js:54152:19
        at isolate (assets/vendor.js:54353:13)
        at assets/vendor.js:54337:14
        at tryCatch (assets/vendor.js:67511:14)
        at Object.invokeCallback (assets/vendor.js:67526:15)
        at assets/vendor.js:69338:21
        at assets/vendor.js:43933:7
        at Queue.invoke (assets/vendor.js:11464:16)
        at Object.Queue.flush (assets/vendor.js:11528:11)

This looks like I'm probably not requiring in a necessary package. Any idea what package `testHelpers.wait` is defined in?

**Comment by paulelliott** [comment]
I'm seeing this exact same thing on a project, fwiw. Also at a loss.

**Comment by rwjblue** [comment]
@paulelliott -  See https://github.com/emberjs/data/pull/3690 for an upstream fix, and https://github.com/emberjs/ember.js/issues/10310#issuecomment-133877589 for a work around you can use in your apps for now.

```javascript
App.initializer({
  name: 'clear-service-store',
  before: ['ember-data'],
  initialize(registry) {
    registry.unregister('service:store');
  }
});
```

**Comment by paulelliott** [comment]
@rwjblue That is a cleaner way to handle the title error of this issue, for sure. :+1:

I am still seeing `TypeError: app.testHelpers.wait is not a function` just like @spinlock99 though.

**Comment by rwjblue** [comment]
@paulelliott - Are you saying that you are getting this error without the patch that @spinlock99 mentioned (clobbering `this.app.registry`)? If you are using that patch: I do not think that clobbering the whole registry will result in good times, so I would definitely suggest using the initializer approach that I linked above.  If you are not using that patch, and you are getting this error on an out of the box setup please open a new issue so we can try to diagnose it.

**Comment by paulelliott** [comment]
I tried @spinlock99's suggestion before you posted the initializer. It worked but left me with the error about `app.testHelpers.wait`.

When you posted the initializer I took that hack out and used that, which yielded the same result. The initializer approach is a much better workaround and that is what I am going with.

The `app.testHelpers.wait` issue is likely related to ember-cli-mocha, which both @spinlock99 and I are using.

**Comment by spinlock99** [comment]
@rwjblue thanks for posting that initializer. Much nicer solution until ember-data is patched. I am still getting the `app.testHelpers.wait` issue. Would you prefer if I closed this issue and opened a new one for that or just continue this thread?

@paulelliott What does your setup look like? Here's the debug from my app (with ember-cli-mocha @ 0.7.0)

    DEBUG: -------------------------------
    DEBUG: Ember      : 1.13.9
    DEBUG: Ember Data : 1.13.11
    DEBUG: jQuery     : 1.11.3
    DEBUG: -------------------------------

**Comment by paulelliott** [comment]
I'm using ember-cli-mocha 0.9.2 with ember-mocha 0.8.0 and:

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.13.7
DEBUG: Ember Data : 1.13.8
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
```

**Comment by rwjblue** [comment]
Can someone make a repro to demo this? I just made http://emberjs.jsbin.com/genolo/edit?html,js that you can use as a base.

**Comment by spinlock99** [comment]
This is very odd. I can't recreate the error using @rwjblue 's jsbin. So, I tried creating a fresh app with ember-cli to see if I could recreate the error there: nope. Then, I compared my `package.json` and `bower.json` to the new, clean, ember-cli app and make sure all the packages were in parity. 

This is where is gets interesting: I did not get the `service:store` error with the fresh ember-cli app but I do still get it with my app. This makes me suspect that the `testHelpers.wait` has the same root cause as the `service:store` issue.

**Comment by NullVoxPopuli** [comment]
I'm getting this error with ember 2.5

![image](https://cloud.githubusercontent.com/assets/199018/15359013/41849b2e-1cd5-11e6-822c-d87c9a940b0d.png)

**Comment by spinlock99** [comment]
@NullVoxPopuli can you post an example using the jsbin or a fresh github repo?

I suspect we haven't closed this issue yet because no one has been able to show an example yet.

Thanks!

**Comment by NullVoxPopuli** [comment]
Here is a repo: https://github.com/NullVoxPopuli/aeonvera-ui/tree/mocha-test

This is the first errorr that shows up

**Comment by NullVoxPopuli** [comment]
here is a travis log, if that helps https://travis-ci.org/NullVoxPopuli/aeonvera-ui/jobs/131395768
(first error)

**Comment by NullVoxPopuli** [comment]
Ok, I added the registry hack:

```
  afterEach(() => {
    // tear down
    application.registry.unregister('session:main');
    application.registry.unregister('session-store:test');

    destroyApp(application);
    server.shutdown();
  });
```

but, now I'm also getting the 
```
TypeError: app.testHelpers.wait is not a function
``` 
problem.

:-(

Does this mean that the test helpers aren't being loaded properly?

I think there is something funky with acceptance testing and mocha right now. :-\

Any ideas?

**Comment by Turbo87** [comment]
https://github.com/emberjs/data/pull/3690 seems to have fixed the original issue. if there are still issues in this area please open a new issue.
