### ISSUE TITLE
Clicking on "failures" transitions to the main app

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli-mocha#90]
The URL changes from `/tests` to `/#`.

Instead, it should filter assertions to display only failed ones.

**Comment by lolmaus** [comment]
So this has been fixed in Mocha 2.3.0: https://github.com/mochajs/mocha/commit/f3c2a0a3e4faa0af6f02efce151b464c406e9467

Is there a reason why `ember-mocha` is locked at `2.2.x`?

**Comment by lolmaus** [comment]
The workaround is to update `bower.json`. Thank druids, Bower's dependency list is flat. You wouldn't be able to pull that out with npm.

```
{
  "dependencies": {
    ...
    "mocha": ">=2.3.4",
    ...
  "resolutions": {
    "mocha": ">=2.3.4"
  }
}
```

**Comment by Turbo87** [comment]
as mentioned in https://github.com/ember-cli/ember-cli-mocha/pull/130 we are using Mocha 2.4.5+ now so I guess this isn't an issue anymore. feel free to reopen is the issue persists.
